version: 2

# Use this if you are referencing modules from a private module registry.
# registries:
#   hcp-terraform:
#     type: terraform-registry
#     url: https://app.terraform.io
#     token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

updates:
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(deps)

  - package-ecosystem: github-actions
    directory: /
    registries: '*'
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
